# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f1a1e63470e476058967ad0a8acd1119f4eec79ab306445352465eb5876b87d28bd8d2b566ce3397d649d067b6629642cd4ae2dedcb5918e9559118694fa67e

test:
  secret_key_base: 343a9efdbc7432b8f4e5c5858b3f3d1fea38bd3b7a3343fdef3b1354e1dfe5c62696754ad9a29b2e899c7f0db170123c8ba03b2e61146874263bdb491e3a23d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
